[theme]
primaryColor="#adffb7"
backgroundColor="#4931c3"
secondaryBackgroundColor="#021f64"
textColor="#f1f1f1"
font="sans serif"


# custom white: #f1f1f1
# green : #adffb7 #
# dark blue : #021f64
# purple1: #32175e
# purple1 : #593692
# purple2: #8455cf
# purple3: #4931c3
# purple4: #5434f3
