[theme]
primaryColor="#A980D6"
backgroundColor="#332478"
secondaryBackgroundColor="#594E92"
textColor="#f1f1f1"
font="sans serif"


# custom white: #f1f1f1
# green : #adffb7 #
# dark blue : #021f64
# purple1: #32175e
# purple1 : #593692
# purple2: #8455cf
# purple3: #4931c3
# purple4: #5434f3


#3736B5
#243493
#594E92
#A980D6
#332478
#C9AFDF


# Colors before modification:
  # primaryColor="#adffb7"
  # backgroundColor="#4931c3"
  # secondaryBackgroundColor="#021f64"
  # textColor="#f1f1f1"
  # font="sans serif"

# green from title: #adffb7
